# SPDX-FileCopyrightText: 2026 Jonas I. Liechti <j-i-l@t4d.ch>
# SPDX-License-Identifier: LGPL-3.0-or-later

## ReadTheDocs configuration.
#

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install --group docs .

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
